// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-LvVx-TmE32W3DL8l7oNJwUR2VOceIJM',
    appId: '1:54999621429:web:2d2b44a4887de31dd4b67c',
    messagingSenderId: '54999621429',
    projectId: 'charmieapp-2346e',
    authDomain: 'charmieapp-2346e.firebaseapp.com',
    storageBucket: 'charmieapp-2346e.appspot.com',
    measurementId: 'G-R27LFQBV12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuA1WXvybDXnm1sJa1mrgu-aXWbhI0GoE',
    appId: '1:54999621429:android:19acbce14d2d0830d4b67c',
    messagingSenderId: '54999621429',
    projectId: 'charmieapp-2346e',
    storageBucket: 'charmieapp-2346e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1sLIk-OXIHx_TkHY58WntdDyipA9psIc',
    appId: '1:54999621429:ios:15a8acc9310e1c5cd4b67c',
    messagingSenderId: '54999621429',
    projectId: 'charmieapp-2346e',
    storageBucket: 'charmieapp-2346e.appspot.com',
    iosBundleId: 'com.example.testProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1sLIk-OXIHx_TkHY58WntdDyipA9psIc',
    appId: '1:54999621429:ios:15a8acc9310e1c5cd4b67c',
    messagingSenderId: '54999621429',
    projectId: 'charmieapp-2346e',
    storageBucket: 'charmieapp-2346e.appspot.com',
    iosBundleId: 'com.example.testProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-LvVx-TmE32W3DL8l7oNJwUR2VOceIJM',
    appId: '1:54999621429:web:de2a121bad0e6fccd4b67c',
    messagingSenderId: '54999621429',
    projectId: 'charmieapp-2346e',
    authDomain: 'charmieapp-2346e.firebaseapp.com',
    storageBucket: 'charmieapp-2346e.appspot.com',
    measurementId: 'G-2ENMFJ8026',
  );
}
